### ISSUE TITLE
[SOLVED] Weird errors when not using input from the tutorial

### ISSUE THREAD

**Issue by someoneEsle** [csunlab/GISF2E#1]
Hello.
I was able to successfully run your Python code as explained in the tutorial (using the input files you provide), and everything worked fine. However, when trying to make it work on the files downloaded from [here](http://download.geofabrik.de/north-america/us/illinois.html) (a website you link to in the tutorial), I get several errors.
Can anyone help me out here?
Thank you very much

`Traceback (most recent call last):
  File "/.../GISF2E_python_v1.10.py", line 262, in <module>
    b = filter(lambda x: (testando['bridge'][x[1][0]] == testando['bridge'][int(x[1][1])]) or (testando['tunnel'][x[1][0]] == testando['tunnel'][int(x[1][1])]), filter(lambda x: len(x[1]) >= 2, zip(a.keys(),a.values())))
  File "/.../GISF2E_python_v1.10.py", line 262, in <lambda>
    b = filter(lambda x: (testando['bridge'][x[1][0]] == testando['bridge'][int(x[1][1])]) or (testando['tunnel'][x[1][0]] == testando['tunnel'][int(x[1][1])]), filter(lambda x: len(x[1]) >= 2, zip(a.keys(),a.values())))
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 1969, in __getitem__
    return self._getitem_column(key)
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 1976, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/lib/python2.7/dist-packages/pandas/core/generic.py", line 1091, in _get_item_cache
    values = self._data.get(item)
  File "/usr/lib/python2.7/dist-packages/pandas/core/internals.py", line 3211, in get
    loc = self.items.get_loc(item)
  File "/usr/lib/python2.7/dist-packages/pandas/core/index.py", line 1759, in get_loc
    return self._engine.get_loc(key)
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:3979)
  File "pandas/index.pyx", line 157, in pandas.index.IndexEngine.get_loc (pandas/index.c:3843)
  File "pandas/hashtable.pyx", line 668, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12265)
  File "pandas/hashtable.pyx", line 676, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12216)
KeyError: 'bridge'`

EDIT: I downloaded the "illinois-latest.shp.zip" file

**Comment by csunlab** [comment]
Hi,

Thanks a lot for your comment. First of all, make sure your 'input' folder only has one type of shapefile. The "illinois-latest.shp.zip" data set has information on railways, waterways, etc. Just use the roads data.

Moreover, we also checked, and deleting the other files may result in an error (some files are created by the OS automatically), so instead, copy and paste the relevant files in your 'input' folder.

Finally, we would advise against running the code on the entire state of Illinois. The run time might be much too long. You may want to crop out only the cities that are of interest. If you really want to run the tool on the entire state, make sure you can leave your computer running for several hours.

Best,

CSUN Lab
